


set(LIBEVENT_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/src/include/libevent/${ANDROID_ABI}/include/)
set(LIBEVENT_LIBRARY ${CMAKE_SOURCE_DIR}/src/include/libevent/${ANDROID_ABI}/lib/libevent_core.a)

set(LIBEVENT_FOUND FALSE)
if (LIBEVENT_INCLUDE_DIR AND LIBEVENT_LIBRARY)
	set(LIBEVENT_FOUND TRUE)
endif()

message("CMAKE_CURRENT_LIST_DIR:" ${CMAKE_CURRENT_LIST_DIR})
message("CMAKE_CURRENT_SOURCE_DIR:" ${CMAKE_CURRENT_SOURCE_DIR})
message("CMAKE_SOURCE_DIR:" ${CMAKE_SOURCE_DIR})

message("LIBEVENT_LIBRARY:" ${LIBEVENT_LIBRARY})
message("LIBEVENT_FOUND:" ${LIBEVENT_FOUND})


